[project]
name = "ralph-writer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.24.0",
    "openai-agents>=0.10.2",
    "pillow>=12.1.1",
    "pyyaml>=6.0",
    "rich>=14.3.3",
    "tiktoken>=0.12.0",
]
